workflows:
    macos-workflow:
      name: macOS Workflow
      environment:
        vars:
          XCODE_PROJECT: "macOS UITesting.xcodeproj"
          XCODE_SCHEME: "macOS UITesting"
          BUNDLE_ID: "com.rudrankriyam.macOS-UITesting"
        xcode: default
        cocoapods: default
      triggering:
        events:
          - push
          - tag
          - pull_request
        branch_patterns:
          - pattern: 'beta'
            include: true
            source: true
      scripts:
        - name: Testing the project for bug-free release
          script: |
            xcode-project run-tests --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
