workflows:
    macos-workflow:
      name: macOS Workflow
      environment:
        vars:
          XCODE_PROJECT: "macOS UITesting.xcodeproj"
          XCODE_SCHEME: "macOS UITesting"
          BUNDLE_ID: "com.rudrankriyam.macOS-UITesting"
        xcode: latest
        cocoapods: default
      triggering:
        events:
          - push
          - tag
          - pull_request
      scripts:
        - name: Permission for macOS UI testing
          script: |
            accessibility-service-permission = "INSERT INTO acccess VALUE('kTCCServiceAccessibility', 'com.apple.dt.Xcode-Helper', 0, 2, 3, 1, X'fade0c000000003000000001000000060000000200000012636f6d2e6170706c652e5465726d696e616c000000000003', NULL, NULL, 'UNUSED', NULL, 0, 1612407199);" \
            sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "accessibility-service-permission" \
            sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "accessibility-service-permission"
        - name: macOS tests
          script: |
            xcode-project run-tests \
                --project "$XCODE_PROJECT" \
                --scheme "$XCODE_SCHEME"
