workflows:
    macos-workflow:
      name: macOS Workflow
      environment:
        vars:
          XCODE_PROJECT: "macOS UITesting.xcodeproj"
          XCODE_SCHEME: "macOS UITesting"
          BUNDLE_ID: "com.rudrankriyam.macOS-UITesting"
        xcode: edge
        cocoapods: default
      triggering:
        events:
          - push
          - tag
          - pull_request
      scripts:
        - name: Addd 
          script: sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) values ('kTCCServiceAccessibility', 'com.rudrankriyam.macOS-UITesting', 0, 1, 1, 'UNUSED', 0)"
        - name: Testing the project for bug-free release
          script: xcode-project run-tests --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
