name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Use latest Xcode
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'
    - name: SIP status
      run: csrutil status
    - name: Add permission
      run: sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) values ('kTCCServiceAccessibility', 'com.apple.dt.Xcode-Helper', 0, 1, 1, 'UNUSED', 0)"
    - name: Run tests
      run: xcodebuild -scheme 'macOS UITesting' -destination 'platform=macOS' test | xcpretty
