name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Use latest Xcode
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'
    - name: Run tests
      run: xcodebuild -scheme 'macOS UITesting' -destination 'platform=macOS' test | xcpretty
